version: '3'
services:
  app:
    build: .
    image: caredoc
    container_name: caredoc_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      # - /var/www/caredoc:/var/www/html
      # # - .:/var/www/caredoc
      # - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./storage:/var/www/storage
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./src/.env:/var/www/.env
      - ./src/.styleci.yml:/var/www/.styleci.yml
      - ./src/README.md:/var/www/README.md
      - ./src/app:/var/www/app
      - ./src/artisan:/var/www/artisan
      - ./src/bootstrap:/var/www/bootstrap
      - ./src/config:/var/www/config
      - ./src/database:/var/www/database
      - ./src/package-lock.json:/var/www/package-lock.json
      - ./src/package.json:/var/www/package.json
      - ./src/phpunit.xml:/var/www/phpunit.xml
      - ./src/public:/var/www/public
      - ./src/resources:/var/www/resources
      - ./src/routes:/var/www/routes
      - ./src/server.php:/var/www/server.php
      - ./src/tests:/var/www/tests
      - ./src/webpack.mix.js:/var/www/webpack.mix.js
      - ./src/laravel-log.job:/var/www/storage/logs/laravel-log.job
    networks:
      - caredoc

  webserver:
    image: nginx:alpine
    container_name: nginxcaredoc
    restart: unless-stopped
    tty: true
    ports:
      - "2022:80"
    volumes:
      # - .:/var/www/caredoc
      # - ./storage/:/etc/nginx/conf.d/
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs:/var/log/nginx
    networks:
      - caredoc
  
  # php:
  #   image: php:8.3-fpm
  #   container_name: caredoc_php
  #   volumes:
  #     # - ./src:/var/www/caredoc
  #     - /var/www/caredoc:/var/www/html
  #   networks:
  #     - caredoc

#NETWORK
networks:
  caredoc:
    driver: bridge

#VOLUMES
volumes:
  lbdata:
    driver: local