version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: caredoc-app
    container_name: caredoc-app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_HOST=caredoc.cluster-c90ggcmwk096.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=caredoc
      - DB_USERNAME=apps_admin
      - DB_PASSWORD=dvHyxp6i0OOiZEsqM2J6
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www

  web:
    image: nginx:latest
    container_name: caredoc-web
    restart: unless-stopped
    ports:
      - "8002:80"
      - "8444:443"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d

volumes:
  dbdata:
