version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: caredoc-app
    container_name: caredoc-app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_HOST=your-rds-endpoint
      - DB_PORT=3306
      - DB_DATABASE=your-database-name
      - DB_USERNAME=your-username
      - DB_PASSWORD=your-password
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www

  web:
    image: nginx:latest
    container_name: caredoc-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d

volumes:
  dbdata:
