version: '3'
services:
  app:
    build: .
    image: caredoc
    container_name: caredoc_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/caredoc
    volumes:
      - .:/var/www/caredoc
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - caredoc

  webserver:
    image: nginx:alpine
    container_name: nginxcaredoc
    restart: unless-stopped
    tty: true
    ports:
      - "2022:80"
    volumes:
      - .:/var/www/caredoc
      - ./storage/:/etc/nginx/conf.d/
    depends_on:
      - php
    networks:
      - caredoc
  
  php:
    image: php:8.3-fpm
    container_name: caredoc_php
    volumes:
      - ./src:/var/www/caredoc
    networks:
      - caredoc

#NETWORK
networks:
  caredoc:
    driver: bridge

#VOLUMES
volumes:
  lbdata:
    driver: local